language: ruby
rvm:
  - 2.2.0
before_install:
  - "echo '--colour' > ~/.rspec"
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis-ci@example.com'
install:
  - bundle install
notifications:
  email: false
