language: ruby
rvm: 2.7.1
cache: bundler
before_install:
  - nvm install 13.12.0
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis-ci@example.com'
  - gem update --system
  - gem install bundler
  - bundler config --global disable_platform_warnings true
install: bundle install
notifications:
  email: false
services:
  - postgresql
